version: '3.8' # Actualizado a la versión más reciente del formato 3
services:
  api:
    image: fastapi-oracle-image:latest
    container_name: fastapi-api  # Nombre fijo para que sea fácil encontrarlo en logs
    restart: always              # ¡VITAL! Si la API se cae o la RAM falla, Docker la levanta sola
    ports:
      - "8000:8000"
    env_file:
      - .env